f = open("test1.txt","w+")
file = open("quiz1.py","r")
data = file.read()
print(data)
f.write(data)
file1 = open("quiz2.py","r")
data1 = file1.read()
print(data1)
f.write(data1)
file2 = open("quiz3.py","r")
data2 = file2.read()
f.write(data2)
file3 = open("quiz7.py","r")
data3 = file3.read()
f.write(data3)
f.close()
