# Generated by Django 2.2.5 on 2019-09-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('FullName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Gender', models.CharField(max_length=10)),
                ('PhoneNumber', models.IntegerField(unique=True)),
                ('Qualification', models.CharField(max_length=50)),
                ('Branch', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=25)),
                ('conPassword', models.CharField(max_length=25)),
            ],
        ),
    ]
