# Generated by Django 2.2.5 on 2019-09-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('Username', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
